/**
 * lib/data.ts
 *
 * All image/video paths are Cloudinary public_ids — fetched directly from
 * the Cloudinary Admin API (scripts/fetch-cloudinary-ids.mjs).
 *
 * Format: "public_id_string"  ← no folder prefix, no extension
 * These IDs are auto-generated by Cloudinary at upload time.
 */

export type EventItem = {
  slug:       string;
  title:      string;
  shortDesc:  string;
  coverImage: string;   // Cloudinary public_id
  videoUrls:  string[]; // Cloudinary public_ids (video resource_type)
  gallery:    string[]; // Cloudinary public_ids (image resource_type)
};

export const events: EventItem[] = [
  {
    slug:      "wedding-photography",
    title:     "Wedding Photography",
    shortDesc: "Cinematic and candid moments from your special day.",
    coverImage: "10_tmddnm",
    videoUrls:  [],
    gallery: [
      "10_tmddnm", "11_jxe9c8", "12_yr9xod", "13_uzbdps", "14_y4vr9q", "15_fdj3vz", "16_zoab6o", "17_gqualc", "18_cfzw3q", "19_j2qoeb", "1_c67hww", "20_otphqs", "21_ftfvun", "25_pxcpk7", "26_pivcu1", "27_i7canw", "28_pk3ouv", "29_pjedxz", "2_zmnh6i", "30_iwbov9", "31_tbv0wv", "32_zc6dk7", "33_uqcazp", "3_nwfmtl", "41_os6lnm", "42_bz8zqf", "43_pfft7h", "44_yzpx4m", "45_w5yeiy", "46_d0bzwe", "47_bkaws1", "48_vosykb", "4_bwhebt", "5_kc1yof", "6_i3fpe6", "76_cvng56", "7_dk6cbi", "8_ezovjy", "9_kfavno",
    ],
  },
  {
    slug:      "naming-ceremony",
    title:     "Naming Ceremony",
    shortDesc: "Beautifully capturing the first milestones of your little one.",
    coverImage: "1_lhiyzb",
    videoUrls:  [],
    gallery: [
      "1_lhiyzb", "2_ru0ho7", "3_vlchyj", "4_ahio2q", "5_cmjhd7", "6_xlvcx8", "7_n22il2", "8_xua4xi",
    ],
  },
  {
    slug:      "baby_shower",
    title:     "Baby Shower",
    shortDesc: "Vibrant colors and joyful traditions captured beautifully.",
    coverImage: "10_poaclr",
    videoUrls:  [],
    gallery: [
      "10_poaclr", "11_cdmaex", "12_mfmv4m", "13_oi094n", "14_bcrv92", "15_j394hz", "19_sxb1mi", "1_kglo1c", "20_ib6ico", "21_ixqwbg", "22_vhcfsp", "23_rjtep8", "24_ympdqh", "25_cysks3", "2_noqrv3", "3_n42ke4", "4_qcqjvt", "5_lylwsr", "6_pbjzjp", "7_eruawi", "8_uvr8rv", "9_rbkddt",
    ],
  },
  {
    slug:      "pre-wedding-shoot",
    title:     "Pre-Wedding Shoot",
    shortDesc: "Romantic storytelling before you tie the knot.",
    coverImage: "108_spozzi",
    videoUrls:  [],
    gallery: [
      "108_spozzi", "109_ofo8vh", "10_at0i7f", "110_iqnb0h", "11_samf3q", "12_awlx9b", "13_zeebiq", "14_izm5xd", "15_h8piyt", "16_afglg5", "17_elurw2", "18_o8vhnl", "19_hk0xs3", "1_zs3bib", "20_fn8prl", "21_ddhzf7", "22_dx7kid", "23_elcids", "24_gssfej", "25_hsfldy", "26_w7ruhj", "27_hqmn3x", "28_xq4v1f", "29_wecwat", "2_oqmvlk", "30_cqb8uz", "31_rmahyr", "32_nfr3pb", "33_h8xwky", "34_gs1p7r", "35_acnaoo", "36_ar9l5h", "37_e27su0", "38_pd1s5x", "39_ok7gr1", "3_nstdha", "40_bzomrz", "41_ifa9mk", "42_t6pnir", "43_a4bowz", "44_llcrn9", "45_t55rjb", "46_bzphmc", "47_eioui4", "48_llhxv1", "49_rglyxn", "4_obkomn", "50_rafq6s", "51_jinlw4", "52_kdqf6f", "53_p9oqa7", "54_ou4ucr", "55_jfxm4v", "56_jsnonm", "57_kflfun", "58_miq6m0", "59_ilelqw", "5_syxl1l", "60_n7yq1w", "61_ghg5lz", "62_jh5tnv", "63_kfx3ws", "64_n262ml", "65_drezno", "66_lzursj", "67_tngaux", "68_jfzcvn", "6_tf5iwx", "70_g5xd9w", "71_cepo4y", "72_jktirk", "73_opvxyq", "74_k3shfy", "75_mgwunj", "76_btnpfo", "77_vrabjx", "78_ahugmb", "79_ibt1kt", "7_r0oyxc", "8_a9nu8q", "9_tnexzx",
    ],
  },
  {
    slug:      "ad-shoot",
    title:     "Ad Shoot",
    shortDesc: "Commercial photography and videography for brands.",
    coverImage: "10_gddz9h",
    videoUrls:  [
      "2_xojalz",
    ],
    gallery: [
      "10_gddz9h", "11_bfv0gj", "12_huxk8w", "13_pf6r8l", "14_ilxkr8", "15_gelqs9", "1_doyq4h", "6_obiph2", "7_xvfrhj", "8_qg1mtr", "9_xmyttz",
    ],
  },
  {
    slug:      "Birthday",
    title:     "Birthday Celebrations",
    shortDesc: "Fun, energy, and memories from grand birthday parties.",
    coverImage: "10_wz2aod",
    videoUrls:  [],
    gallery: [
      "10_wz2aod", "11_nf57zl", "12_giolnl", "1_fejmp5", "2_gm086h", "3_ltqlp9", "4_u9a4ux", "5_nrawt1", "6_u8fut8", "7_uyvjpu", "8_l6kibs",
    ],
  },
  {
    slug:      "Fashion",
    title:     "Fashion & Portfolio",
    shortDesc: "High-end fashion photography and modeling portfolios.",
    coverImage: "10_bmuohf",
    videoUrls:  [],
    gallery: [
      "10_bmuohf", "11_tpnnak", "12_si0coz", "13_r8brbd", "14_s50qrw", "15_x0pjq2", "16_zf76mh", "1_anifbr", "1_ytrlax", "2_kznbvu", "3_tvzy7j", "4_yy2qcz", "5_o6g5ek", "6_toqpql", "7_yttgjk", "8_plcrag", "9_wafhq5",
    ],
  },
  {
    slug:      "Corporate",
    title:     "Corporate Events",
    shortDesc: "Professional coverage for seminars, launches, and corporate galas.",
    coverImage: "10_piy9i4",
    videoUrls:  [
      "1_y74yf9",
    ],
    gallery: [
      "10_piy9i4", "10_uhsll5", "11_derba4", "14_y5nwsd", "15_n0cmkb", "18_qdcear", "19_jmsapl", "1_qwaiwp", "1_ulermg", "20_mgorbh", "21_wjo2ra", "22_zuxqmw", "23_lkvxc8", "24_iv3psh", "2_rxg1bm", "3_ia7ilc", "4_ecs0kt", "5_cxnug2", "6_jexkfo", "7_ce7ohe", "7_yxfxzd", "8_cvrzfo", "8_vecgcx", "9_xfle9s", "9_xkrfkd",
    ],
  },
  {
    slug:      "real_estate",
    title:     "Real Estate",
    shortDesc: "High-quality visuals showcasing properties to attract buyers.",
    coverImage: "10_vuqjjj",
    videoUrls:  [],
    gallery: [
      "10_vuqjjj", "11_nvi3k1", "12_mb7rsx", "13_gzpmau", "14_niaomi", "15_cn5lj0", "16_d0azfc", "17_lepa7j", "18_gchkhu", "19_xnigvh", "1_hxpjh7", "20_kzwzni", "21_oyx4wv", "22_xjkqah", "23_ow4yml", "24_xsijwj", "25_xg4i2b", "26_tfkpk7", "27_k6u6t4", "28_tqffrw", "29_zuyfgg", "2_id06hq", "30_p5x0wn", "3_n0zj0n", "4_dcjzjy", "5_lwnzqd", "6_d7kz3i", "7_vtrzow", "8_cd54gd", "9_ouelmw",
    ],
  },
  {
    slug:      "Films",
    title:     "FILMS",
    shortDesc: "Cinematic storytelling through high-quality visuals.",
    coverImage: "17_mhoa6m",
    videoUrls:  [],
    gallery: [
      "17_mhoa6m", "18_rhdyan", "19_xbmvjl", "2_hw4ufw", "2_rs6hvx", "3_t8ejbn", "4_kpgoaw", "5_xymhx7", "6_lcep3q", "7_mh4kni", "8_j6jvh5",
    ],
  },
  {
    slug:      "bts",
    title:     "BTS",
    shortDesc: "Behind-the-scenes capturing the creative process and teamwork.",
    coverImage: "10_jn5yyn",
    videoUrls:  [],
    gallery: [
      "10_jn5yyn", "11_svoggy", "12_nkwfeb", "13_rrinkd", "14_j9dhxk", "15_f0l3cx", "16_cdlqzx", "17_eozygz", "18_r8i0cz", "19_ordtpr", "1_trgxaf", "20_i6mosh", "21_ddpnd5", "22_ymfpfn", "23_s8jp4i", "24_mbfsmi", "25_ui9llj", "26_wktxp5", "27_uc2xfc", "28_kfne8e", "29_sytmvx", "2_genadp", "30_jb162f", "31_l2u2rp", "32_sfnmch", "33_rnjzdm", "34_uwnyuk", "35_k0sme3", "36_g3goob", "37_rd7f66", "38_xapsvo", "39_cfkvbf", "3_k1nqsa", "40_klz0jj", "41_vklkzx", "4_bjx1nf", "5_geinji", "6_e4gwvj", "7_feqnda", "8_sdk9ay", "9_xokcqo",
    ],
  },
  {
    slug:      "engagement",
    title:     "Engagement",
    shortDesc: "Capturing the beautiful beginning of your forever.",
    coverImage: "10_zgvj6p",
    videoUrls:  [],
    gallery: [
      "10_zgvj6p", "11_h6seoh", "12_bq07p1", "13_xmbhy9", "14_o7nubm", "15_f2apxc", "16_a5ahop", "17_nbsito", "18_kq1bxp", "19_kabai1", "1_gbfheb", "2_tw6nv2", "31_igypmf", "32_hrpsg3", "33_vdkttb", "34_aycax5", "35_ddtfza", "36_xuv1u4", "37_lusqnj", "38_hemiod", "39_mo1fe9", "3_pq3tcd", "40_t5flwy", "4_ljdqmh", "5_zrytx3", "6_bc1zvf", "7_ryzlw5", "8_jsa0bk", "9_l0swvc",
    ],
  },
  {
    slug:      "new_born",
    title:     "New Born",
    shortDesc: "Precious and pure moments of your newborn baby.",
    coverImage: "10_dzmfqj",
    videoUrls:  [
      "3_u4ulun",
    ],
    gallery: [
      "10_dzmfqj", "11_w4b7uf", "12_xtgwqc", "13_afgrsc", "14_r31mtf", "15_qmumkg", "16_gwfmhb", "17_xj8jzv", "18_f5ttl0", "19_ll2aim", "1_uvmd6c", "20_bt1srf", "21_fhqkdh", "22_gzvg8z", "23_hryryf", "24_aioyme", "25_shucq9", "26_w37gm3", "27_rzirkc", "28_cywvbu", "29_ug0uix", "2_nkobmp", "30_jx0vgj", "31_iufbor", "32_m1r3py", "33_pmqzwi", "34_oc8jun", "35_isq6ip", "36_sexbqn", "37_f1ekaf", "38_rx0op0", "39_kf6wkz", "3_g3u0gm", "40_hatvhj", "41_p0o3ow", "42_xhytte", "43_yz64zb", "46_lqvk54", "47_ua4gj3", "48_ad2bwq", "49_svp4us", "4_p9gypf", "50_cciyos", "51_lrvvhy", "5_fif9yr", "67_refge2", "68_iykuhy", "69_vx4cch", "6_auy296", "70_bcb6t0", "71_ndouo7", "72_r6gfet", "76_zdzota", "77_ljqi3i", "78_oepjxk", "79_f04zua", "7_yawwmn", "8_xrjcoc", "9_mel21f",
    ],
  },
];

// ─── Hero slideshow images (homepage) ─────────────────────────────────────────
export const heroImages: string[] = [
  events.find(e => e.slug === "wedding-photography")?.coverImage || "",
  events.find(e => e.slug === "naming-ceremony")?.coverImage || "",
  events.find(e => e.slug === "baby_shower")?.coverImage || "",
];